# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.FloatField(),
        ),
    ]
