# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_auto_20170614_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bmc',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
