# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_profile_bmc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bmc',
            new_name='bmr',
        ),
    ]
